name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    name: Main

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          # Value already defaults to true, but `persist-credentials` is required to push new commits to the repository.
          persist-credentials: true
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run the default task
        run: bundle exec rake

      - name: Generate calendar feeds
        run: bin/generate_tgj_calendar

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Automated: Update TGJ calendar feeds"
